name: dokuro_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  intl: ^0.17.0 # Add this line

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_appauth: ^4.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  url_launcher: ^6.1.0
  graphql: ^5.1.1
  simple_moment: ^1.1.1
  fl_chart: ^0.50.6
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.11
  rxdart: ^0.27.4
  timezone: ^0.8.0
  collection: ^1.16.0
  colorize: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml`
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true # flutter gen-l10n
  assets:
    - assets/
    - assets/images/
    - assets/images/welcome_image.png
    - assets/images/video_place_here.png
    - assets/images/facebook-reactions-emoticons/png-16/
    - assets/images/facebook-reactions-emoticons/png-24/
    - assets/images/facebook-reactions-emoticons/png-32/
    - assets/images/facebook-reactions-emoticons/png-48/
    - assets/images/facebook-reactions-emoticons/png-64/
    - assets/images/facebook-reactions-emoticons/png-96/
    - assets/images/facebook-reactions-emoticons/png-128/
    - assets/images/facebook-reactions-emoticons/png-1024/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
